name: Opera Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup VM
      run: |
        sudo apt-get update
        sudo apt-get install dbus-x11
        sudo /usr/bin/Xvfb :99 -screen 0 1024x768x24 &
        wget https://iridium-cloud-support.s3.amazonaws.com/opera-developer_65.0.3445.0_amd64.deb
        sudo dpkg -i opera-*.deb
    - name: Build with Gradle
      run: ./gradlew build -x test
      env:
        ossrhPassword: ${{ secrets.ossrhPassword }}
        ossrhUsername: ${{ secrets.ossrhUsername }}
        DisableSigning: true
    - name: Run Opera tests
      run: ./gradlew test -Dopera.binary=/usr/bin/opera -DtestBrowsers=${TEST_SUITE}
      env:
        DISPLAY: ":99.0"
        TEST_SUITE: "{'browsers':['Opera'],'runNegTests':false,'runSimpleTests':false}"
        ossrhPassword: ${{ secrets.ossrhPassword }}
        ossrhUsername: ${{ secrets.ossrhUsername }}
        DisableSigning: true
